### ISSUE TITLE
Do you have plans for this documentation to support multiple languages?

### ISSUE THREAD

**Issue by tinydew4** [GitbookIO/documentation#46] opened 2016-10-10 05:17 UTC
@AaronO @SamyPesse @Soreine 

I've a document translated into [Korean](https://tinydew4.gitbooks.io/gitbook/content/).
However, the current structure of the official repository isn't visible for multilingual supports.
Do you have any plans for this?

**Comment by Soreine** [comment] 2016-10-10 08:07
That's very nice. We could make this documentation multilingual. The problem is we don't have any translators. So we would not be able to keep all versions up to date with the English reference version.

Nonetheless, we could list translated versions with their last time updated, so that people know if a translation is likely to be out-of-date:

----

# Choose a language

- [English]() (Last update: 07/10/2016)

Translations:

- [Korean]() (Translated from 01/10/2016 version)
- [Spanish]() (Translated from 20/09/2016 version)
- Etc.

----

These dates would need to be maintained by hand. Translators should always specify the date of the published English version their translation was based on.

If we don't do that, we rather not integrate any translation into the official repo, but simply list external links for translations.

PS: This repo is the old one. The doc now lives here https://github.com/GitbookIO/gitbook/tree/master/docs

**Comment by Soreine** [comment] 2016-10-10 08:23
Closed this one in favor of https://github.com/GitbookIO/gitbook/issues/1560

**Closed by Soreine** 2016-10-10 08:23 UTC
